version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "naruse666"
  # Terraform
  - package-ecosystem: "terraform"
    directory: "terraform/env"
    schedule:
      interval: "weekly"
    reviewers:
      - "naruse666"
