version: "3.9"
services: 
  api-server:
    build: .
    ports: 
      - "8010:8010"
    env_file:
      - .env
# これいる？？　parameter storeのゴミ？
    volumes:
      - ~/.aws/:/root/.aws:ro
networks:
  api-server:
    name: api-network
    driver: bridge
