# syntax=docker/dockerfile:1
FROM golang:1.20.4
#FROM --platform=linux/amd64 golang:1.20.4

RUN groupadd -r app \
  && useradd -r -g app -d /app app
RUN mkdir /app && chown app:app /app
WORKDIR /app
USER app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

RUN go build -o /ipro

EXPOSE 8080

CMD [ "/ipro" ]
