name: Suicide Build and Push
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'app/api_server/suicide'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/api_server/suicide
    steps:
    - uses: actions/checkout@v3    

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{secrets.AWS_ROLE_ARN}}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t suicide . -f Containerfile
        docker tag suicide:latest ${{ secrets.ECR_SUICIDE_REPO }}
        docker push ${{ secrets.ECR_SUICIDE_REPO }}
