name: Terraform Plan
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches: 
      - deploy
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  terraform_plan:
    name: plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - root_module: terraform/env
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ matrix.root_module }}
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ matrix.root_module }}
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        working-directory: ${{ matrix.root_module }}
      - uses: actions/github-script@v6
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `## Target env: ${{ matrix.root_module }}
            #### Terraform Init \`${{ steps.init.outcome }}\`
            #### Terraform Validate \`${{ steps.validate.outcome }}\`
            #### Terraform Plan \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - root_module: terraform/env
    steps:
      - uses: actions/checkout@v3
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ matrix.root_module }}
          soft_fail: true # dont break build

